[package]
name = "rocket_csrf"
description = "Rocket fairing and guard for csrf protection"
version = "0.1.0"
authors = ["Trinity Pointard <trinity.pointard@insa-rennes.fr>"]
repository = "https://github.com/fdb-hiroshima/rocket_csrf"
readme = "README.md"
license = "GPL-3.0"
keywords = ["rocket", "csrf", "security"]

[dependencies]
csrf = "~0.3.0"
data-encoding = "~2.1.1"
rand = "~0.5.2"
serde = "~1.0"
time = "~0.1.40"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
rev = "55459db7732b9a240826a5c120c650f87e3372ce"

#test dependancy
[dependencies.rocket_codegen]
git = "https://github.com/SergioBenitez/Rocket"
rev = "55459db7732b9a240826a5c120c650f87e3372ce"
